version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-pizza
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pizza-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: postgres://admin:postgres@postgres:5432/pizza-db?sslmode=disable
    depends_on:
      - postgres

volumes:
  pgdata: